---
output:
  html_document:
    #css: !expr here::here("assets", "styles_pjp.css") 
    css: assets/styles_pjp.css
    #theme: cerulean  #o flatly(gris)  united (naranja) spacelab(azulito) o yeti o faltly o sandstone
    #highlight: kate 
    self_contained: yes
    number_sections: no
    #includes:
       #in_header: google-analytics.html
    toc: true
    toc_float: true
    #code_folding: show
    #self_contained: TRUE
---



```{r klippy, echo = FALSE}
klippy::klippy(position = c("top", "right")) #- remotes::install_github("rlesur/klippy")
```

<br>

<div class = "blue">
**Trabajos**: los estudiantes del curso, como parte de la evaluación continua, tuvieron que presentar dos trabajos, uno individual y otro en equipo. Puedes verlos en los siguientes enlaces:
</div>



<br><br>

## Trabajos en equipo

<br>

- **Jesús Lloret Quero**, **Vicent Mompo Crespo** y **Francisco Martínez Caballero** presentaron el trabajo [Inflación en tiempos de pandemia](https://fran2200.github.io/trabajo_BigData_equipo/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/fran2200/trabajo_BigData_equipo){target="_blank"}.  Las `slides` para la presentación están [aquí](https://fran2200.github.io/trabajo_BigData_slides/){target="_blank"}.

<br> 


- **Pau Piera Palacios**, **Mario García Zamora** y **Pau Piera Palacios** presentaron el trabajo [Sistema de Pensiones Español](https://paupiera23.github.io/trabajo_BigData_equipo/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/paupiera23/trabajo_BigData_equipo){target="_blank"}.  Las `slides` para la presentación están [aquí](https://paupiera23.github.io/trabajo_BigData_slides/){target="_blank"}.


<br> 


- **Aleixandra Blasco**, **Alba Ibañez** y **Vanesa Regueiro Raña** presentaron el trabajo [Spotify en la actualidad y su espíritu navideño](https://vanesarr.github.io/trabajo_BigData_equipo/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/vanesarr/trabajo_BigData_equipo){target="_blank"}.  Las `slides` para la presentación están [aquí](https://vanesarr.github.io/trabajo_BigData_slides/){target="_blank"}.

<br> 


- **Teodoro D'Agostino**, **Jorge González** y **Aurora Lloret** presentaron el trabajo [Principales conclusiones de la piratería desde 1993 hasta nuestros días](https://joorge0603.github.io/trabajo_BigData_equipo/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/joorge0603/trabajo_BigData_equipo){target="_blank"}.  Las `slides` para la presentación están [aquí](https://joorge0603.github.io/trabajo_BigData_slides/){target="_blank"}.

<br> 


- **Carlos García Castilla**, **Alejandro García Segarra** y **Cayetano Fernando Romero Monteagudo** presentaron el trabajo [Alt +  Formula 1](https://cayetano108.github.io/trabajo_BigData_equipo/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/cayetano108/trabajo_BigData_equipo){target="_blank"}.  Las `slides` para la presentación están [aquí](https://cayetano108.github.io/trabajo_BigData_slides/){target="_blank"}.

<br> 


- **Galina Lopez Zinchuk**, **Fatima Makroud Saidi** y **Damian Pérez Soler** presentaron el trabajo [Análisis del impacto medioambiental de la producción agrícola en Europa](https://damianps14.github.io/trabajo_BigData_equipo/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/damianps14/trabajo_BigData_equipo){target="_blank"}.  Las `slides` para la presentación están [aquí](https://damianps14.github.io/trabajo_BigData_slides/){target="_blank"}.

<br> 



- **Julio Gonzalez Miralles**, **Pedro Julián López Mejías** y **Lawrence Daniel Phillips Bates** presentaron el trabajo [¿Se vive bien en la Comunidad Valenciana](https://lorenzo1999.github.io/trabajo_BigData_equipo/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/lorenzo1999/trabajo_BigData_equipo){target="_blank"}.  Las `slides` para la presentación están [aquí](https://lorenzo1999.github.io/trabajo_BigData_slides/){target="_blank"}.

<br> 


- **Carolina Espí García**, **José Pineda Torres** y **Jialing Zhang** presentaron el trabajo [Evolución del precio del crudo](https://Pitojo.github.io/trabajo_BigData_equipo/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/Pitojo/trabajo_BigData_equipo){target="_blank"}.  Las `slides` para la presentación están [aquí](https://Pitojo.github.io/trabajo_BigData_slides/){target="_blank"}.

<br> 


- **Anna Chesa Llorens**, **Lorenzo Chirchirillo** y **Alicja Młynek** presentaron el trabajo [Análisis de las mejores 100 universidades del mundo](https://AlicjaMl.github.io/trabajo_BigData_equipo/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/AlicjaMl/trabajo_BigData_equipo){target="_blank"}.  Las `slides` para la presentación están [aquí](https://AlicjaMl.github.io/trabajo_BigData_slides/){target="_blank"}.

<br> 


- **Alejandro Calderero**, **Mario de Benito** y **Alejandro Pérez** presentaron el trabajo [Análisis de criptomonedas, evolución y actualidad](https://alejandrocp00.github.io/trabajo_BigData_equipo/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/alejandrocp00/trabajo_BigData_equipo){target="_blank"}.  Las `slides` para la presentación están [aquí](https://alejandrocp00.github.io/trabajo_BigData_slides/){target="_blank"}.

<br> 


- **Alba Estela**, **Melanie Neufcour** y **Mireia Yangüez** presentaron el trabajo [FAST FOOD. Análisis del restaurante McDonald’s](https://meneuf.github.io/trabajo_BigData_equipo/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/meneuf/trabajo_BigData_equipo){target="_blank"}.  Las `slides` para la presentación están [aquí](https://meneuf.github.io/trabajo_BigData_slides/){target="_blank"}.

<br> 



<br><br>

## Trabajos individuales

------------------

Aquí irán los enlaces a vuestros trabajos individuales.

<br>



<br><br>

------------------------


<div class = "blue">
<center>[Aquí](https://perezp44.github.io/intro-ds-20-21-web/07-trabajos.html){target="_blank"} puedes ver los trabajos de los estudiantes del curso pasado. Por ejemplo [este](https://nosan5.github.io/trabajo_BigData_equipo/){target="_blank"}. </center>

</div>


------------------------

<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>
